/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Cancel exclusion": {                            "en": "Cancel exclusion",                                "de": "Ausschluss aufheben",                             "ru": "Отмена исключения",                               "pt": "Cancelar exclusão",                               "nl": "Uitsluiting annuleren",                           "fr": "Annuler l'exclusion",                             "it": "Annulla esclusione",                              "es": "Cancelar exclusión",                              "pl": "Anuluj wykluczenie",                              "zh-cn": "取消排除"},
    "Cancel inclusion": {                            "en": "Cancel inclusion",                                "de": "Einbinden abbrechen",                             "ru": "Отмена включения",                                "pt": "Cancelar inclusão",                               "nl": "Annuleer opname",                                 "fr": "Annuler l'inclusion",                             "it": "Annulla l'inclusione",                            "es": "Cancelar inclusión",                              "pl": "Anuluj włączenie",                                "zh-cn": "取消收录"},
    "Devices": {                                     "en": "Devices",                                         "de": "Geräte",                                          "ru": "приборы",                                         "pt": "Aparelhos",                                       "nl": "apparaten",                                       "fr": "Dispositifs",                                     "it": "dispositivi",                                     "es": "Dispositivos",                                    "pl": "Pomysłowość",                                     "zh-cn": "设备"},
    "Exclude device": {                              "en": "Exclude device",                                  "de": "Gerät entfernen",                                 "ru": "Исключить устройство",                            "pt": "Excluir dispositivo",                             "nl": "Apparaat uitsluiten",                             "fr": "Exclure un appareil",                             "it": "Escludi dispositivo",                             "es": "Excluir dispositivo",                             "pl": "Wyklucz urządzenie",                              "zh-cn": "排除装置"},
    "Include device": {                              "en": "Include device",                                  "de": "Gerät einbinden",                                 "ru": "Включить устройство",                             "pt": "Incluir dispositivo",                             "nl": "Apparaat opnemen",                                "fr": "Inclure l'appareil",                              "it": "Includi dispositivo",                             "es": "Incluir dispositivo",                             "pl": "Uwzględnij urządzenie",                           "zh-cn": "包含装置"},
    "Name": {                                        "en": "Name",                                            "de": "Name",                                            "ru": "название",                                        "pt": "Nome",                                            "nl": "Naam",                                            "fr": "prénom",                                          "it": "Nome",                                            "es": "Nombre",                                          "pl": "Imię",                                            "zh-cn": "名称"},
    "Network map": {                                 "en": "Network map",                                     "de": "Netzwerkkarte",                                   "ru": "Карта сети",                                      "pt": "Mapa de rede",                                    "nl": "Netwerk kaart",                                   "fr": "Carte du réseau",                                 "it": "Mappa di rete",                                   "es": "Mapa de red",                                     "pl": "Mapa sieci",                                      "zh-cn": "网络图"},
    "No devices present": {                          "en": "No devices present",                              "de": "Keine Geräte vorhanden",                          "ru": "Устройства отсутствуют",                          "pt": "Nenhum dispositivo presente",                     "nl": "Geen apparaten aanwezig",                         "fr": "Aucun appareil présent",                          "it": "Nessun dispositivo presente",                     "es": "No hay dispositivos presentes",                   "pl": "Brak urządzeń",                                   "zh-cn": "没有设备"},
    "Select serial port": {                          "en": "Select serial port",                              "de": "Serielle Schnittstelle auswählen",                "ru": "Выберите последовательный порт",                  "pt": "Selecionar porta serial",                         "nl": "Selecteer seriële poort",                         "fr": "Sélectionnez le port série",                      "it": "Seleziona la porta seriale",                      "es": "Seleccionar puerto serie",                        "pl": "Wybierz port szeregowy",                          "zh-cn": "选择串口"},
    "Settings": {                                    "en": "Settings",                                        "de": "Einstellungen",                                   "ru": "настройки",                                       "pt": "Configurações",                                   "nl": "instellingen",                                    "fr": "Paramètres",                                      "it": "impostazioni",                                    "es": "Configuraciones",                                 "pl": "Ustawienia",                                      "zh-cn": "设定值"},
    "Status": {                                      "en": "Status",                                          "de": "Status",                                          "ru": "Положение дел",                                   "pt": "Status",                                          "nl": "staat",                                           "fr": "Statut",                                          "it": "Stato",                                           "es": "Estado",                                          "pl": "Status",                                          "zh-cn": "状态"},
    "Type": {                                        "en": "Type",                                            "de": "Typ",                                             "ru": "Тип",                                             "pt": "Tipo",                                            "nl": "Type",                                            "fr": "Type",                                            "it": "genere",                                          "es": "Tipo",                                            "pl": "Rodzaj",                                          "zh-cn": "类型"},
    "alive": {                                       "en": "alive",                                           "de": "erreichbar",                                      "ru": "в живых",                                         "pt": "vivo",                                            "nl": "levend",                                          "fr": "vivant",                                          "it": "vivo",                                            "es": "viva",                                            "pl": "żywy",                                            "zh-cn": "活"},
    "asleep": {                                      "en": "asleep",                                          "de": "schläft",                                         "ru": "спящий",                                          "pt": "adormecido",                                      "nl": "in slaap",                                        "fr": "endormi",                                         "it": "addormentato",                                    "es": "dormido",                                         "pl": "we śnie",                                         "zh-cn": "睡着了"},
    "awake": {                                       "en": "awake",                                           "de": "wach",                                            "ru": "бодрствующий",                                    "pt": "acordado",                                        "nl": "wakker",                                          "fr": "éveillé",                                         "it": "sveglio",                                         "es": "despierto",                                       "pl": "obudzić",                                         "zh-cn": "苏醒"},
    "dead": {                                        "en": "dead",                                            "de": "tot",                                             "ru": "мертвых",                                         "pt": "morto",                                           "nl": "dood",                                            "fr": "mort",                                            "it": "morto",                                           "es": "muerto",                                          "pl": "nie żyje",                                        "zh-cn": "死"},
    "loading...": {                                  "en": "loading...",                                      "de": "Wird geladen...",                                 "ru": "загрузка ...",                                    "pt": "Carregando...",                                   "nl": "bezig met laden...",                              "fr": "chargement...",                                   "it": "Caricamento in corso...",                         "es": "cargando...",                                     "pl": "Ładuję...",                                       "zh-cn": "载入中..."},
    "none selected": {                               "en": "none selected",                                   "de": "nichts ausgewählt",                               "ru": "не выбрано, ничего не выбрано",                   "pt": "nenhum selecionado",                              "nl": "geen geselecteerd",                               "fr": "aucune sélection",                                "it": "Nessuno selezionato",                             "es": "ninguna seleccionada",                            "pl": "nie wybrano",                                     "zh-cn": "未选择"},
    "unknown": {                                     "en": "unknown",                                         "de": "unbekannt",                                       "ru": "неизвестный",                                     "pt": "desconhecido",                                    "nl": "onbekend",                                        "fr": "inconnu",                                         "it": "sconosciuto",                                     "es": "desconocido",                                     "pl": "nieznany",                                        "zh-cn": "未知"},
    "zwave2 adapter settings": {                     "en": "Adapter settings for Z-Wave 2",                   "de": "Adaptereinstellungen für Z-Wave 2",               "ru": "Настройки адаптера для zwave2",                   "pt": "Configurações do adaptador para zwave2",          "nl": "Adapterinstellingen voor zwave2",                 "fr": "Paramètres d'adaptateur pour zwave2",             "it": "Impostazioni dell'adattatore per zwave2",         "es": "Ajustes del adaptador para zwave2",               "pl": "Ustawienia adaptera dla zwave2",                  "zh-cn": "zwave2的适配器设置"},
    "Heal network": {                                "en": "Heal network",                                    "de": "Heilen-Netzwerk",                                 "ru": "Исцелить сети",                                   "pt": "Curar rede",                                      "nl": "Helen netwerk",                                   "fr": "Guérir réseau",                                   "it": "Guarire rete",                                    "es": "Sanar la red",                                    "pl": "Leczyć sieci",                                    "zh-cn": "医治网络"},
    "Heal network finished": {                       "en": "Heal network finished",                           "de": "Heilen-Netzwerk fertig",                          "ru": "Исцелить сеть",                                   "pt": "Curar rede terminado",                            "nl": "Helen netwerk klaar",                             "fr": "Guérir réseau fini",                              "it": "Guarire rete finito",                             "es": "Sanar la red terminado",                          "pl": "Leczyć sieć",                                     "zh-cn": "愈合的网络中完成的"},
};